=== stasadj/immunization-is/XML docs/interesovanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="iskazivanje_interesovanja_za_vakcinaciju">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pacijent"/>
        <xs:element ref="zeljena_opstina_vakcinacije"/>
        <xs:element ref="odabir_vakcina"/>
      </xs:sequence>
      <xs:attribute name="datum" use="required" type="xs:date"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pacijent">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="drzavljanstvo"/>
        <xs:element ref="jmbg"/>
        <xs:element ref="puno_ime"/>
        <xs:element ref="kontakt_informacije"/>
        <xs:element ref="dobrovoljni_davalac_krvi"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="drzavljanstvo" type="xs:string"/>
  <xs:element name="jmbg">
    <xs:simpleType>
      <xs:restriction base="xs:positiveInteger">
        <xs:pattern value="[0-9]{13}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="puno_ime">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="licno_ime"/>
        <xs:element ref="prezime"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="licno_ime" type="xs:string"/>
  <xs:element name="prezime" type="xs:string"/>
  <xs:element name="kontakt_informacije">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="email_adresa"/>
        <xs:element ref="fiksni_telefon"/>
        <xs:element ref="mobilni_telefon"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="email_adresa">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[^@]+@[^\.]+\..+"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="fiksni_telefon">
    <xs:simpleType>
      <xs:restriction base="xs:positiveInteger">
        <xs:pattern value="[0-9]{9,10}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="mobilni_telefon">
    <xs:simpleType>
      <xs:restriction base="xs:positiveInteger">
        <xs:pattern value="[0-9]{9,11}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="zeljena_opstina_vakcinacije" type="xs:string"/>
  <xs:element name="odabir_vakcina">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="opcija"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="opcija" type="xs:string"/>
  <xs:element name="dobrovoljni_davalac_krvi" type="xs:boolean"/>
</xs:schema>

=== stasadj/immunization-is/backend/src/main/resources/documents/interesovanje.xml
<?xml version="1.0" encoding="UTF-8"?>
<iskazivanje_interesovanja_za_vakcinaciju xmlns="http://www.ftn.uns.ac.rs/interesovanje/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema#"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/interesovanje/ interesovanje.xsd" 
    datum="2021-02-02"
    about="http://www.ftn.uns.ac.rs/interesovanje/1111111111111">
    <pacijent about="http://www.ftn.uns.ac.rs/licni-podaci/1111111111111">
        <drzavljanstvo property="pred:ima_drzavljanstvo" datatype="xs:string">Dr≈æavljanin Republike Srbije</drzavljanstvo>
        <jmbg property="pred:ima_jmbg" datatype="xs:string">1111111111111</jmbg>
        <puno_ime property="pred:se_zove" datatype="xs:string">Dina Petrov</puno_ime>
        <kontakt_informacije>
            <email_adresa>xxxx@xxxxx.com</email_adresa>
            <fiksni_telefon>023111111</fiksni_telefon>
            <mobilni_telefon>0611111111</mobilni_telefon>
        </kontakt_informacije>
        <dobrovoljni_davalac_krvi property="pred:je_dobrovoljni_davalac_krvi" datatype="xs:string">true</dobrovoljni_davalac_krvi>
    </pacijent>
    <zeljena_opstina_vakcinacije>Novi Sad</zeljena_opstina_vakcinacije>
    <odabir_vakcina>
        <opcija>
            Pfizer-BioNTech
        </opcija>
        <opcija>
            AstraZeneca
        </opcija>
        <opcija>
            Moderna
        </opcija>
    </odabir_vakcina>
</iskazivanje_interesovanja_za_vakcinaciju>
