=== stasadj/immunization-is/XML docs/potvrda_o_vakcinaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="potvrda_o_vakcinaciji">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sifra_potvrde"/>
        <xs:element ref="datum_izdavanja_potvrde"/>
        <xs:element ref="qr_kod"/>
        <xs:element ref="licni_podaci"/>
        <xs:element ref="vakcinacije"/>
      </xs:sequence>
      <xs:attribute name="potreban_pecat" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sifra_potvrde" type="xs:positiveInteger"/>
  <xs:element name="datum_izdavanja_potvrde" type="xs:date"/>
  <xs:element name="qr_kod" type="xs:anyURI"/>
  <xs:element name="licni_podaci">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ime"/>
        <xs:element ref="prezime"/>
        <xs:element ref="pol"/>
        <xs:element ref="jmbg"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ime" type="xs:string"/>
  <xs:element name="prezime" type="xs:string"/>
  <xs:element name="pol">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="M"/>
        <xs:enumeration value="Z"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="jmbg">
    <xs:simpleType>
      <xs:restriction base="xs:positiveInteger">
        <xs:pattern value="[0-9]{13}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="vakcinacije">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="vakcinacija" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="zdravstvena_ustanova" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="vakcinacija">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="naziv_vakcine"/>
        <xs:element ref="datum_davanja"/>
        <xs:element ref="broj_serije"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naziv_vakcine" type="xs:string"/>
  <xs:element name="datum_davanja" type="xs:date"/>
  <xs:element name="broj_serije" type="xs:positiveInteger"/>
</xs:schema>

=== stasadj/immunization-is/common/src/main/resources/documents/potvrda_o_vakcinaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<potvrda_o_vakcinaciji xmlns="http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema#"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji potvrda_o_vakcinaciji.xsd"
    potreban_pecat="false" about="http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/0123456789">
    <sifra_potvrde>0123456789</sifra_potvrde>
    <datum_izdavanja_potvrde>2021-11-21</datum_izdavanja_potvrde>
    <qr_kod>zdravstvena-ustanova.gov.rs/putanja/ka/dokumentu</qr_kod>
    <licni_podaci about="http://www.ftn.uns.ac.rs/licni-podaci/2001990111111" vocab="http://www.ftn.uns.ac.rs/rdf/predicate/">
        <ime_prezime property="pred:se_zove" datatype="xs:string">Pera Peric</ime_prezime>
        <pol property="pred:ima_pol" datatype="xs:string">M</pol>
        <jmbg property="pred:ima_jmbg" datatype="xs:string">2001990111111</jmbg>
    </licni_podaci>
    <vakcinacije zdravstvena_ustanova="Dom Zdravlja Novi Sad">
        <vakcinacija>
            <naziv_vakcine>Pfizer-BioNTech</naziv_vakcine>
            <datum_davanja>2021-04-10</datum_davanja>
            <broj_serije>14</broj_serije>
        </vakcinacija>
        <vakcinacija>
            <naziv_vakcine>Pfizer-BioNTech</naziv_vakcine>
            <datum_davanja>2021-10-10</datum_davanja>
            <broj_serije>15</broj_serije>
        </vakcinacija>
    </vakcinacije>
</potvrda_o_vakcinaciji>
