=== stasadj/immunization-is/XML docs/saglasnost.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/saglasnost"
    xmlns="http://www.ftn.uns.ac.rs/saglasnost"
    xmlns:util="http://ftn.uns.ac.rs/util">
    
    <xs:import namespace="http://ftn.uns.ac.rs/util" schemaLocation="util.xsd"/>
    
    <xs:element name="obrazac_saglasnosti_za_imunizaciju">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="informacije_o_pacijentu"/>
                <xs:element ref="evidencija_o_vakcinaciji"/>
            </xs:sequence>
            <xs:attribute name="datum" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="informacije_o_pacijentu">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="drzavljanstvo"/>
                <xs:element ref="puno_ime"/>
                <xs:element ref="pol"/>
                <xs:element ref="datum_i_mesto_rodjenja"/>
                <xs:element ref="prebivaliste"/>
                <xs:element ref="kontakt_informacije"/>
                <xs:element ref="radni_status"/>
                <xs:element ref="zanimanje_zaposlenog"/>
                <xs:element ref="ustanova_socijalne_zastite"/>
                <xs:element ref="izjava_saglasnosti"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="drzavljanstvo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="srpsko_drzavljanstvo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="jmbg" type="util:jmbg"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="strano_drzavljanstvo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="naziv_stranog_drzavljanstva" type="xs:string"/>
                            <xs:element name="broj_pasosa_ili_ebs" type="util:broj_pasosa"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="puno_ime">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="prezime" type="xs:string"/>
                <xs:element name="licno_ime" type="xs:string"/>
                <xs:element name="ime_roditelja" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pol" type="util:pol"/>
    <xs:element name="datum_i_mesto_rodjenja">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datum_rodjenja" type="xs:date"/>
                <xs:element name="mesto_rodjenja" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="prebivaliste">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ulica" type="xs:string"/>
                <xs:element name="broj" type="xs:string"/>
                <xs:element name="mesto" type="xs:string"/>
                <xs:element name="opstina" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="kontakt_informacije">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fiksni_telefon" type="util:fiksni"/>
                <xs:element name="mobilni_telefon" type="util:mobilni"/>
                <xs:element name="email_adresa" type="util:email"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="radni_status" type="xs:string"/>
    <xs:element name="zanimanje_zaposlenog" type="xs:string"/>
    <xs:element name="ustanova_socijalne_zastite">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pacijent_koristi_zastitu" type="xs:boolean"/>
                <xs:element name="naziv_sedista" type="xs:string"/>
                <xs:element name="opstina_sedista" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="izjava_saglasnosti">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="saglasan" type="xs:boolean"/>
                <xs:element name="naziv_imunoloskog_leka" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="evidencija_o_vakcinaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="zdravstvena_ustanova"/>
                <xs:element ref="izvrsena_imunizacija"/>
                <xs:element ref="kontraindikacija"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="zdravstvena_ustanova">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naziv" type="xs:string"/>
                <xs:element name="vakcinacijski_punkt" type="xs:string"/>
                <xs:element name="informacije_o_lekaru">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ime" type="xs:string"/>
                            <xs:element name="prezime" type="xs:string"/>
                            <xs:element name="faksimil" type="xs:string"/>
                            <xs:element name="broj_telefona" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="izvrsena_imunizacija">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="vakcina"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="kontraindikacija">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="privremene_kontraindikacije"/>
                <xs:element ref="trajne_kontraindikacije"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="informacije_o_lekaru">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ime" type="xs:string"/>
                <xs:element name="prezime" type="xs:string"/>
                <xs:element name="faksimil" type="xs:string"/>
                <xs:element name="broj_telefona">
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:pattern value="[0-9]{9,10}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="vakcina">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="broj_doze" type="xs:positiveInteger"/>
                <xs:element name="naziv" type="xs:string"/>
                <xs:element name="datum_davanja" type="xs:date"/>
                <xs:element name="nacin_davanja">
                    <xs:simpleType>
                        <xs:restriction base="xs:string"/>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ekstremitet">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="([L][R])|([D][R])"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="serija" type="xs:positiveInteger"/>
                <xs:element name="proizvodjac" type="xs:string"/>
                <xs:element name="nezeljena_reakcija" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="privremene_kontraindikacije">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datum_utvrdjivanja" type="nillableDate" minOccurs="0"
                    nillable="true"/>
                <xs:element name="dijagnoza" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="trajne_kontraindikacije">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="odluka_komisije" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="nillableDate">

        <xs:union memberTypes="xs:dateTime emptyString"/>

    </xs:simpleType>

    <xs:simpleType name="emptyString">

        <xs:restriction base="xs:string">

            <xs:length value="0"/>

        </xs:restriction>

    </xs:simpleType>

</xs:schema>

=== stasadj/immunization-is/XML docs/saglasnost.xml
<?xml version="1.0" encoding="UTF-8"?>
<obrazac_saglasnosti_za_imunizaciju xmlns="http://www.ftn.uns.ac.rs/saglasnost"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/saglasnost saglasnost.xsd" 
    datum="2021-06-11">
    <informacije_o_pacijentu>
        <drzavljanstvo>
            <srpsko_drzavljanstvo>
                <jmbg>1234567890123</jmbg>
            </srpsko_drzavljanstvo>
            <strano_drzavljanstvo>
                <naziv_stranog_drzavljanstva>Austrija</naziv_stranog_drzavljanstva>
                <broj_pasosa_ili_ebs>123456489</broj_pasosa_ili_ebs>
            </strano_drzavljanstvo>
        </drzavljanstvo>
        <puno_ime>
            <prezime>Petrov</prezime>
            <licno_ime>Dina</licno_ime>
            <ime_roditelja>Branislav</ime_roditelja>
        </puno_ime>
        <pol>Å½</pol>
        <datum_i_mesto_rodjenja>
            <datum_rodjenja>1999-06-04</datum_rodjenja>
            <mesto_rodjenja>Zrenjanin</mesto_rodjenja>
        </datum_i_mesto_rodjenja>
        <prebivaliste>
            <ulica>Bulevar Despota Stefana</ulica>
            <broj>7a</broj>
            <mesto>Novi Sad</mesto>
            <opstina>Novi Sad</opstina>
        </prebivaliste>
        <kontakt_informacije>
            <fiksni_telefon>111111111</fiksni_telefon>
            <mobilni_telefon>1111111111</mobilni_telefon>
            <email_adresa>xxxxxx@xxxx.com</email_adresa>
        </kontakt_informacije>
        <radni_status>student</radni_status>
        <zanimanje_zaposlenog></zanimanje_zaposlenog>
        <ustanova_socijalne_zastite>
            <pacijent_koristi_zastitu>true</pacijent_koristi_zastitu>
            <naziv_sedista></naziv_sedista>
            <opstina_sedista></opstina_sedista>
        </ustanova_socijalne_zastite>
        <izjava_saglasnosti>
            <saglasan>true</saglasan>
            <naziv_imunoloskog_leka></naziv_imunoloskog_leka>
        </izjava_saglasnosti>
    </informacije_o_pacijentu>
    <evidencija_o_vakcinaciji>
        <zdravstvena_ustanova>
            <naziv></naziv>
            <vakcinacijski_punkt></vakcinacijski_punkt>
            <informacije_o_lekaru>
                <ime></ime>
                <prezime></prezime>
                <faksimil></faksimil>
                <broj_telefona></broj_telefona>
            </informacije_o_lekaru>
        </zdravstvena_ustanova>
        <izvrsena_imunizacija>
            <vakcina>
                <broj_doze>1</broj_doze>
                <naziv>AstraZeneca</naziv>
                <datum_davanja>2021-04-04</datum_davanja>
                <nacin_davanja>IM</nacin_davanja>
                <ekstremitet>LR</ekstremitet>
                <serija>43872</serija>
                <proizvodjac>AstraZeneca</proizvodjac>
                <nezeljena_reakcija></nezeljena_reakcija>
            </vakcina>
            <vakcina>
                <broj_doze>2</broj_doze>
                <naziv>AstraZeneca</naziv>
                <datum_davanja>2021-06-04</datum_davanja>
                <nacin_davanja>IM</nacin_davanja>
                <ekstremitet>LR</ekstremitet>
                <serija>93872</serija>
                <proizvodjac>AstraZeneca</proizvodjac>
                <nezeljena_reakcija></nezeljena_reakcija>
            </vakcina>
        </izvrsena_imunizacija>
        <kontraindikacija>
            <privremene_kontraindikacije>
                <datum_utvrdjivanja></datum_utvrdjivanja>
                <dijagnoza></dijagnoza>
            </privremene_kontraindikacije>
            <trajne_kontraindikacije>
                <odluka_komisije></odluka_komisije>
            </trajne_kontraindikacije>
        </kontraindikacija> 
    </evidencija_o_vakcinaciji>
</obrazac_saglasnosti_za_imunizaciju>

=== stasadj/immunization-is/backend/src/main/resources/documents/saglasnost.xml
<?xml version="1.0" encoding="UTF-8"?>
<obrazac_saglasnosti_za_imunizaciju xmlns="http://www.ftn.uns.ac.rs/saglasnost/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema#"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/saglasnost/ saglasnost.xsd"
    broj="0000000001" datum="2021-06-11"
    about="http://www.ftn.uns.ac.rs/saglasnost/0000000001">
    <informacije_o_pacijentu about="http://www.ftn.uns.ac.rs/licni-podaci/1234567890123">
        <drzavljanstvo>
            <srpsko_drzavljanstvo>
                <jmbg property="pred:ima_jmbg" datatype="xs:string">1234567890123</jmbg>
            </srpsko_drzavljanstvo>
        </drzavljanstvo>
        <puno_ime>
            <ime_prezime property="pred:se_zove" datatype="xs:string">Dina Petrov</ime_prezime>
            <ime_roditelja>Branislav</ime_roditelja>
        </puno_ime>
        <pol property="pred:ima_pol" datatype="xs:string">Å½</pol>
        <datum_i_mesto_rodjenja>
            <datum_rodjenja property="pred:je_rodjen" datatype="xs:string">1999-06-04</datum_rodjenja>
            <mesto_rodjenja property="pred:je_rodjen_u" datatype="xs:string">Zrenjanin</mesto_rodjenja>
        </datum_i_mesto_rodjenja>
        <prebivaliste about="http://www.ftn.uns.ac.rs/prebivaliste/1234567890123">
            <ulica property="pred:nalazi_se_u_ulici" datatype="xs:string">Bulevar Despota Stefana</ulica>
            <broj property="pred:nalazi_se_na_broju" datatype="xs:string">7a</broj>
            <mesto property="pred:nalazi_se_u_mestu" datatype="xs:string">Novi Sad</mesto>
            <opstina property="pred:nalazi_se_u_opstini" datatype="xs:string">Novi Sad</opstina>
        </prebivaliste>
        <kontakt_informacije>
            <fiksni_telefon>111111111</fiksni_telefon>
            <mobilni_telefon>1111111111</mobilni_telefon>
            <email_adresa>xxxxxx@xxxx.com</email_adresa>
        </kontakt_informacije>
        <radni_status property="pred:ima_radni_status" datatype="xs:string">student</radni_status>
        <zanimanje_zaposlenog></zanimanje_zaposlenog>
        <ustanova_socijalne_zastite>
            <pacijent_koristi_zastitu>true</pacijent_koristi_zastitu>
            <naziv_sedista></naziv_sedista>
            <opstina_sedista></opstina_sedista>
        </ustanova_socijalne_zastite>
        <izjava_saglasnosti>
            <saglasan>true</saglasan>
            <naziv_imunoloskog_leka></naziv_imunoloskog_leka>
        </izjava_saglasnosti>
    </informacije_o_pacijentu>
    <evidencija_o_vakcinaciji>
        <zdravstvena_ustanova>
            <naziv property="pred:vakcinisan_u" datatype="xs:string"></naziv>
            <vakcinacijski_punkt></vakcinacijski_punkt>
            <informacije_o_lekaru>
                <ime></ime>
                <prezime></prezime>
                <faksimil></faksimil>
                <broj_telefona></broj_telefona>
            </informacije_o_lekaru>
        </zdravstvena_ustanova>
        <izvrsena_imunizacija>
            <vakcina>
                <broj_doze>1</broj_doze>
                <naziv>AstraZeneca</naziv>
                <datum_davanja>2021-04-04</datum_davanja>
                <nacin_davanja>IM</nacin_davanja>
                <ekstremitet>LR</ekstremitet>
                <serija>43872</serija>
                <proizvodjac>AstraZeneca</proizvodjac>
                <nezeljena_reakcija></nezeljena_reakcija>
            </vakcina>
            <vakcina>
                <broj_doze>2</broj_doze>
                <naziv>AstraZeneca</naziv>
                <datum_davanja>2021-06-04</datum_davanja>
                <nacin_davanja>IM</nacin_davanja>
                <ekstremitet>LR</ekstremitet>
                <serija>93872</serija>
                <proizvodjac>AstraZeneca</proizvodjac>
                <nezeljena_reakcija></nezeljena_reakcija>
            </vakcina>
        </izvrsena_imunizacija>
        <kontraindikacija>
            <privremene_kontraindikacije>
                <datum_utvrdjivanja></datum_utvrdjivanja>
                <dijagnoza></dijagnoza>
            </privremene_kontraindikacije>
            <trajne_kontraindikacije>
                <odluka_komisije></odluka_komisije>
            </trajne_kontraindikacije>
        </kontraindikacija> 
    </evidencija_o_vakcinaciji>
</obrazac_saglasnosti_za_imunizaciju>
