=== stasadj/immunization-is/backend/src/main/resources/documents/izvestaj_o_imunizaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/izvestaj-o-imunizaciji"
    xmlns="http://www.ftn.uns.ac.rs/izvestaj-o-imunizaciji">

    <xs:element name="izvestaj_o_imunizaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="meta_podaci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="period_od">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:attribute name="property" use="required"
                                                type="xs:string" fixed="obuhvata_period_od"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="period_do">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:attribute name="property" use="required"
                                                type="xs:string" fixed="obuhvata_period_do"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="datum_izdavanja">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:attribute name="property" use="required"
                                                type="xs:string" fixed="izdato"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element default="0" name="broj_dokumenata_o_interesovanju" type="xs:unsignedInt"/>
                <xs:element default="0" name="broj_zahteva_za_digitalni_sertifikat"
                    type="xs:unsignedInt"/>
                <xs:element default="0" name="broj_izdatih_digitalnih_sertifikata"
                    type="xs:unsignedInt"/>
                <xs:element name="raspodela_datih_vakcina_po_rednom_broju_doze">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="3" name="doza">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="1" name="redni_broj"
                                            type="xs:positiveInteger"/>
                                        <xs:element name="broj_datih_doza" type="xs:unsignedInt"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ukupno_dato" type="xs:unsignedInt"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="raspodela_datih_vakcina_po_proizvodjacima">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="4" name="proizvodjac">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="naziv" type="xs:string"/>
                                        <xs:element name="broj_datih_doza" type="xs:unsignedInt"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about" use="required" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== stasadj/immunization-is/common/src/main/resources/documents/izvestaj_o_imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>

<izvestaj_o_imunizaciji xmlns="http://www.ftn.uns.ac.rs/izvestaj-o-imunizaciji/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema#"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/izvestaj-o-imunizaciji/ izvestaj_o_imunizaciji.xsd" 
    about="http://www.ftn.uns.ac.rs/izvestaj/2021-08-01-2021-09-01">
    
    <meta_podaci>
        <period_od property="pred:obuhvata_period_od" datatype="xs:string">2021-08-01</period_od>
        <period_do property="pred:obuhvata_period_do" datatype="xs:string">2021-09-01</period_do>
        <datum_izdavanja property="pred:izdato" datatype="xs:string">2021-11-09</datum_izdavanja>
    </meta_podaci>
    
    <broj_dokumenata_o_interesovanju>2758</broj_dokumenata_o_interesovanju>
    <broj_zahteva_za_digitalni_sertifikat>453</broj_zahteva_za_digitalni_sertifikat>
    <broj_izdatih_digitalnih_sertifikata>428</broj_izdatih_digitalnih_sertifikata>
    
    <raspodela_datih_vakcina_po_rednom_broju_doze ukupno_dato="3225">
        <doza>
            <redni_broj>1</redni_broj>
            <broj_datih_doza>1789</broj_datih_doza>
        </doza>
        <doza>
            <redni_broj>2</redni_broj>
            <broj_datih_doza>1276</broj_datih_doza>
        </doza>
        <doza>
            <redni_broj>3</redni_broj>
            <broj_datih_doza>160</broj_datih_doza>
        </doza>
    </raspodela_datih_vakcina_po_rednom_broju_doze>
    
    <raspodela_datih_vakcina_po_proizvodjacima>
        <proizvodjac>
            <naziv>Pfizer, BioNTech</naziv>
            <broj_datih_doza>1625</broj_datih_doza>
        </proizvodjac>
        <proizvodjac>
            <naziv>Sinopharm</naziv>
            <broj_datih_doza>1100</broj_datih_doza>
        </proizvodjac>
        <proizvodjac>
            <naziv>Sputnik V</naziv>
            <broj_datih_doza>356</broj_datih_doza>
        </proizvodjac>
        <proizvodjac>
            <naziv>Astra Zeneca, Oxford</naziv>
            <broj_datih_doza>144</broj_datih_doza>
        </proizvodjac>
    </raspodela_datih_vakcina_po_proizvodjacima>
    
</izvestaj_o_imunizaciji>
