=== stasadj/immunization-is/backend/src/main/resources/documents/zahtev_za_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/zahtev-za-sertifikat"
    xmlns="http://www.ftn.uns.ac.rs/zahtev-za-sertifikat"
    xmlns:util="http://ftn.uns.ac.rs/util">
    
    <xs:import namespace="http://ftn.uns.ac.rs/util" schemaLocation="util.xsd"/>

    <xs:element name="zahtev_za_sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="podnosilac_zahteva">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ime" type="xs:string"/>
                            <xs:element name="prezime" type="xs:string"/>
                            <xs:element name="datum_rodjenja" type="xs:date"/>
                            <xs:element name="pol" type="util:pol"/>
                            <xs:element name="jmbg" type="util:jmbg"/>
                            <xs:element name="broj_pasosa" type="util:broj_pasosa"/>
                            <xs:element name="razlog_za_podnosenje_zahteva" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="mesto_izdavanja" type="xs:string"/>
            <xs:attribute name="datum_izdavanja" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== stasadj/immunization-is/backend/src/main/resources/documents/zahtev_za_sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>

<zahtev_za_sertifikat xmlns="http://www.ftn.uns.ac.rs/zahtev-za-sertifikat/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zahtev-za-sertifikat/ zahtev_za_sertifikat.xsd" 
    about="http://www.ftn.uns.ac.rs/zahtev-za-sertifikat/0234567891234">
    
    <meta_podaci>
        <mesto_izdavanja property="ima_mesto_izdavanja">Novi Sad</mesto_izdavanja>
        <datum_izdavanja property="ima_datum_izdavanja">2021-10-01</datum_izdavanja>
    </meta_podaci>
    
    <podnosilac_zahteva about="http://www.ftn.uns.ac.rs/licni-podaci/0234567891234">
        <ime_prezime property="se_zove">Petar Petrović</ime_prezime>
        <datum_rodjenja property="je_rodjen">1987-01-01</datum_rodjenja>
        <pol property="ima_pol">M</pol>
        <jmbg property="ima_jmbg">0234567891234</jmbg>
        <broj_pasosa property="ima_broj_pasosa">123456789</broj_pasosa>
        <razlog_za_podnosenje_zahteva>Lični zahtev</razlog_za_podnosenje_zahteva>
    </podnosilac_zahteva>
    
</zahtev_za_sertifikat>
