=== stasadj/immunization-is/common/src/main/resources/documents/zahtev_za_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/zahtev-za-sertifikat/"
    xmlns="http://www.ftn.uns.ac.rs/zahtev-za-sertifikat/" xmlns:util="http://ftn.uns.ac.rs/util"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/predicate/">

    <xs:import namespace="http://ftn.uns.ac.rs/util" schemaLocation="util.xsd"/>

    <xs:element name="zahtev_za_sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="meta_podaci">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="mesto_izdavanja">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="property" use="required"
                                                type="xs:string" fixed="pred:ima_mesto_izdavanja"/>
                                            <xs:attribute name="datatype" use="required"
                                                type="xs:string" fixed="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="datum_izdavanja">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:attribute name="property" use="required"
                                                type="xs:string" fixed="pred:ima_datum_izdavanja"/>
                                            <xs:attribute name="datatype" use="required"
                                                type="xs:string" fixed="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="status_zahteva">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="util:status_zahteva_value">
                                            <xs:attribute name="property" use="required"
                                                type="xs:string" fixed="pred:ima_status"/>
                                            <xs:attribute name="datatype" use="required"
                                                type="xs:string" fixed="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="podnosilac_zahteva">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ime_prezime" type="util:ime_prezime"/>
                            <xs:element name="datum_rodjenja" type="util:datum_rodjenja"/>
                            <xs:element name="pol" type="util:pol"/>
                            <xs:element name="jmbg" type="util:jmbg"/>
                            <xs:element name="broj_pasosa" type="util:broj_pasosa"/>
                            <xs:element name="razlog_za_podnosenje_zahteva" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="about" use="required" type="xs:anyURI"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about" use="required" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== stasadj/immunization-is/common/src/main/resources/documents/zahtev_za_sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>

<zahtev_za_sertifikat xmlns="http://www.ftn.uns.ac.rs/zahtev-za-sertifikat/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema#"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zahtev-za-sertifikat/ zahtev_za_sertifikat.xsd" 
    about="http://www.ftn.uns.ac.rs/zahtev-za-sertifikat/0234567891234">
    
    <meta_podaci>
        <mesto_izdavanja property="pred:ima_mesto_izdavanja" datatype="xs:string">Novi Sad</mesto_izdavanja>
        <datum_izdavanja property="pred:ima_datum_izdavanja" datatype="xs:string">2021-10-01</datum_izdavanja>
        <status_zahteva property="pred:ima_status" datatype="xs:string">NA CEKANJU</status_zahteva>
    </meta_podaci>
    
    <podnosilac_zahteva about="http://www.ftn.uns.ac.rs/licni-podaci/0234567891234">
        <ime_prezime property="pred:se_zove" datatype="xs:string">Petar Petrović</ime_prezime>
        <datum_rodjenja property="pred:je_rodjen" datatype="xs:string">1987-01-01</datum_rodjenja>
        <pol property="pred:ima_pol" datatype="xs:string">M</pol>
        <jmbg property="pred:ima_jmbg" datatype="xs:string">0234567891234</jmbg>
        <broj_pasosa property="pred:ima_broj_pasosa" datatype="xs:string">123456789</broj_pasosa>
        <razlog_za_podnosenje_zahteva>Lični zahtev</razlog_za_podnosenje_zahteva>
    </podnosilac_zahteva>
    
</zahtev_za_sertifikat>
